apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: the-etcd-cluster
  namespace: example-com
spec:
  size: 3
  repository: mspreitz/etcd
  version: "e5f2e9e6d98f5dbd2be2c5b2f7ea74bc2dbec76f"
  pod:
    etcdEnv:
    - name: ETCD_METRICS
      value: extensive
    - name: ETCD_LISTEN_METRICS_URLS
      value: http://0.0.0.0:9732
    - name: ETCD_DEBUG
      value: "true"
    labels:
      kos-app: kos-etcd
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9732"
    nodeSelector:
      kos-role/netcd: "true"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              kos-app: kos-etcd
