apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example:subnets-validator
rules:
- apiGroups:
  - network.example.com
  resources:
  - subnets
  - subnets/status
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
