apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example:connection-agent
rules:
- apiGroups:
  - network.example.com
  resources:
  - networkattachments
  verbs:
  - list
  - watch
- apiGroups:
  - network.example.com
  resources:
  - networkattachments/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
