apiVersion: v1
kind: Service
metadata:
  name: network-api
  namespace: example-com
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    kos-app: network-apiserver
