{
 "title": "KOS Externals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "99%ile Percentile Subnet Create-to-Validated Latency secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"ok\"}[1m]))",
     "legendFormat": "valid "
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"err\"}[1m]))",
     "legendFormat": "conflicting"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Subnet Validation Delay due to Validator Downtime",
   "type": "graph",
   "description": "The absolute number of subnets that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 statusErr={{ statusErr }}"
    },
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_count / kos_subnet_validator_subnet_create_to_validated_latency_seconds_count",
     "legendFormat": "waiters / total statusErr={{ statusErr }}"
    },
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_sum / kos_subnet_validator_validation_delay_due_to_downtime_seconds_count",
     "legendFormat": "avg wait secs statusErr={{ statusErr }}"
    }
   ]
  },
  {
   "title": "99%ile Address Controller Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_last_client_write_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "address last_client_wr={{ last_client_wr }} contention={{ contention }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_last_client_write_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "lock last_client_wr={{ last_client_wr }} contention={{ contention }}"
    }
   ]
  },
  {
   "title": "Address Assignment Delay due to Controllers Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    },
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_count / scalar(sum(kos_ipam_last_client_write_to_address_latency_seconds_count))",
     "legendFormat": "waiters / total last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    },
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_sum / kos_ipam_address_delay_due_to_downtime_seconds_count",
     "legendFormat": "avg delay secs last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    }
   ]
  },
  {
   "title": "Address Contention",
   "type": "graph",
   "description": "Fraction of attempt to allocate an address that fail because none is available",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - rate(kos_ipam_address_contention_bucket{le=\"0\"}[1m]) / ignoring (le) rate(kos_ipam_address_contention_bucket{le=\"+Inf\"}[1m]) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Local Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "Local Interface Creation Delay due to CA Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 {{ node_name }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / on(node_name) group_left sum(kos_agent_last_client_write_to_local_ifc_latency_seconds_count) by (node_name)",
     "legendFormat": "waiters / total {{ node_name }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_sum",
     "legendFormat": "avg delay secs {{ node_name }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Attachment Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_status_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Remote Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "Remote Interface Creation Delay due to Remote CA Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count / on(node_name) group_left sum(kos_agent_last_client_write_to_remote_ifc_latency_seconds_count) by (node_name)",
     "legendFormat": "waiters / total {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_sum / kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count",
     "legendFormat": "avg delay secs {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Local Interface to Remote Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_impl_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "virtual network relevance delay secs, per-node",
   "type": "graph",
   "description": "Per-node sum of the delays between the recorded virtual network relevance times and the real relevance times.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_vn_relevance_aggregate_delay_seconds",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99%ile of Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_exec_duration_secs_bucket{what=\"postCreate\"}[1m]))",
     "legendFormat": "{{ node }} {{ lgComplaints }}"
    }
   ]
  },
  {
   "title": "Average Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_duration_secs_sum{what=\"postCreate\"}[1m])/rate(kos_agent_attachment_exec_duration_secs_count{what=\"postCreate\"}[1m])",
     "legendFormat": "{{ node }} {{ lgComplaints }}"
    }
   ]
  },
  {
   "title": "Ping Tests/sec, by Exit Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_status_count{what=\"postCreate\"}[1m])",
     "legendFormat": "{{ node }} {{ exitStatus }} {{ lgComplaints }}"
    }
   ]
  }
 ]
}