{
 "title": "Kubernetes 1.18 apiservers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*ipam.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ipam total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*connection-agent.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ca total"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=\"429\"}[1m])) without (component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 429"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=\"404\"}[1m])) without (component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 404"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"4..\",code!=\"429\",code!=\"404\"}[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 4other"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 5XX"
    }
   ]
  },
  {
   "title": "90th Percentile Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope))",
     "legendFormat": "90th {{ instance }} {{ resource }}/{{ subresource }}"
    }
   ]
  },
  {
   "title": "Avg Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope) / sum(rate(apiserver_request_duration_seconds_count{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope)",
     "legendFormat": "avg {{ instance }} {{ resource }}/{{ subresource }}"
    }
   ]
  },
  {
   "title": "1sec high-water-mark of Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{ instance }} {{ requestKind }}"
    }
   ]
  },
  {
   "title": "Current Number of Long-Running Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (group,version)",
     "legendFormat": "{{ instance }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "longrunning, sum over instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (instance,group,version)",
     "legendFormat": "{{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "TokenReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"tokenreviews\"}[1m])) without (component,group,version,resource,subresource,scope)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "SubjectAccessReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"subjectaccessreviews\"}[1m])) without (component,group,version,resource,subresource,scope)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "Go Heap Bytes In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{ instance }} {{ job }}" }
   ]
  },
  {
   "title": "Go GC CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  }
 ]
}