{
 "title": "Resource Usage Per Node",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Throughput on eth[0-3]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\", interface=~\"eth[0-3]\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} xmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{id=\"/\", interface=~\"eth[0-3]\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} recv"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{id=\"/\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "fs bytes in use",
   "type": "graph",
   "description": "filesystem bytes in use by devices named /dev/vd.*",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev/vd.*\"}) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}