{
 "title": "apiserver request rates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "apiserver request rates",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_count[1m])",
     "legendFormat": "{{ instance }} {{ verb }} {{ resource }} {{ scope }} {{ code }} {{ client }}"
    }
   ]
  }
 ]
}
{
 "title": "apiserver 1.18 request rates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "apiserver request rates",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[1m])) without (group,version)",
     "legendFormat": "{{ instance }} {{ verb }} {{ resource }}/{{ subresource }} {{ scope }} {{ code }}"
    }
   ]
  }
 ]
}
{
 "title": "Driver metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "go MemStats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"kubernetes-nodes-driver\"}",
     "legendFormat": "SysBytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"kubernetes-nodes-driver\"}",
     "legendFormat": "HeapInUseBytes"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Etcd by Prometheus",
 "description": "Dashboard for the etcd cluster of Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_is_leader{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{job=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "Failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_proposals_failed_total{job=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"kubernetes-etcd\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"kubernetes-etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "99th %ile Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "90th %ile net RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "round(histogram_quantile(0.9, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"kubernetes-etcd\"}[5m])) by (instance, le, To)), 0.00001)",
     "legendFormat": "from {{instance}} to {{ To }}"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"kubernetes-etcd\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"kubernetes-etcd\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"kubernetes-etcd\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"kubernetes-etcd\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"kubernetes-etcd\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total{job=\"kubernetes-etcd\"}",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "etcd_server_proposals_applied_total{job=\"kubernetes-etcd\"}",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"kubernetes-etcd\"})",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-nodes-cadvisor\",id=\"/system.slice/etcd.service\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/system.slice/etcd.service\",job=\"kubernetes-nodes-cadvisor\"}) by (instance)",
     "legendFormat": "Working set {{ instance }}"
    },
    {
     "expr": "sum (container_memory_usage_bytes{id=\"/system.slice/etcd.service\",job=\"kubernetes-nodes-cadvisor\"}) by (instance)",
     "legendFormat": "Usage {{ instance }}"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-etcd\"}",
     "legendFormat": "proc res mem {{ instance }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(etcd_network_client_grpc_received_bytes_total{job=\"kubernetes-etcd\"}[1m])) by (instance)) + (sum(rate(etcd_network_client_grpc_sent_bytes_total{job=\"kubernetes-etcd\"}[1m])) by (instance)) + (sum(rate(etcd_network_peer_sent_bytes_total{job=\"kubernetes-etcd\"}[1m])) by (instance)) + (sum(rate(etcd_network_peer_received_bytes_total{job=\"kubernetes-etcd\"}[1m])) by (instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{job=\"kubernetes-etcd\"}[1m]))",
     "legendFormat": "\tThe latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{job=\"kubernetes-etcd\"}[1m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "/dev/vda I/O rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{device=\"/dev/vda\",id=\"/system.slice/etcd.service\",job=\"kubernetes-nodes-cadvisor\"}[1m])) by (instance)",
     "legendFormat": "Write {{ instance }}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{device=\"/dev/vda\",id=\"/system.slice/etcd.service\",job=\"kubernetes-nodes-cadvisor\"}[1m])) by (instance)",
     "legendFormat": "Read {{ instance }}"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{job=\"kubernetes-etcd\"}[1m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  }
 ]
}
{
 "title": "Non-Kubernetes Etcd by Prometheus",
 "description": "Dashboard for etcd clusters NOT of Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_is_leader{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{job!=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "Failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_proposals_failed_total{job!=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "99th %ile Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job!=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job!=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "90th %ile Network RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "round(histogram_quantile(0.9, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job!=\"kubernetes-etcd\"}[5m])) by (instance, le, To)), 0.00001)",
     "legendFormat": "from {{instance}} to {{ To }}"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job!=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job!=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposal Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_failed_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "failed @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_server_proposals_committed_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "committed @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_server_proposals_applied_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "applied @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job!=\"kubernetes-etcd\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Raft Proposal Totals",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total{job!=\"kubernetes-etcd\"}",
     "legendFormat": "committed @ {{ instance }}"
    },
    {
     "expr": "etcd_server_proposals_applied_total{job!=\"kubernetes-etcd\"}",
     "legendFormat": "applied @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_pending{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\".*etcd.*\",container_label_io_kubernetes_pod_name!~\".*etcd-operator.*\"}[1m])) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\".*etcd.*\",container_label_io_kubernetes_pod_name!~\".*etcd-operator.*\"}",
     "legendFormat": "Working set @ {{ instance }}"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\".*etcd.*\",container_label_io_kubernetes_pod_name!~\".*etcd-operator.*\"}",
     "legendFormat": "Usage @ {{ instance }}"
    },
    {
     "expr": "process_resident_memory_bytes{kos_app=\"kos-etcd\"}",
     "legendFormat": "proc res mem @ {{ node_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "Received (gRPC clients) @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "Transmit (gRPC clients) @ {{ instance }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])) by (instance)",
     "legendFormat": "Receive (cAdvisor) @ {{ instance }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])) by (instance)",
     "legendFormat": "Transmit (cAdvisor) @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Disks Utilizations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "WAL fsync @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "BE commit  @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem I/O Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container_label_io_kubernetes_pod_name=~\".*etcd.*\",container_label_io_kubernetes_pod_name!~\".*etcd-operator.*\"}[1m])",
     "legendFormat": "Writes @ {{ instance }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{container_label_io_kubernetes_pod_name=~\".*etcd.*\",container_label_io_kubernetes_pod_name!~\".*etcd-operator.*\"}[1m])",
     "legendFormat": "Reads @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Utilization by Snapshot Saves",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_snap_save_total_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "golang runtime from pods",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MemStats.SysBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"kubernetes-pods\"}",
     "legendFormat": "{{ kubernetes_pod_name }} {{ node_name }}"
    }
   ]
  },
  {
   "title": "SysBytes-HeapReleasedBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"kubernetes-pods\"} - go_memstats_heap_released_bytes{job=\"kubernetes-pods\"}",
     "legendFormat": "{{ kubernetes_pod_name }} {{ node_name }}"
    }
   ]
  }
 ]
}
{
 "title": "KOS Externals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "99%ile Percentile Subnet Create-to-Validated Latency secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"ok\"}[1m]))",
     "legendFormat": "valid "
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"err\"}[1m]))",
     "legendFormat": "conflicting"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Subnet Validation Delay due to Validator Downtime",
   "type": "graph",
   "description": "The absolute number of subnets that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 statusErr={{ statusErr }}"
    },
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_count / kos_subnet_validator_subnet_create_to_validated_latency_seconds_count",
     "legendFormat": "waiters / total statusErr={{ statusErr }}"
    },
    {
     "expr": "kos_subnet_validator_validation_delay_due_to_downtime_seconds_sum / kos_subnet_validator_validation_delay_due_to_downtime_seconds_count",
     "legendFormat": "avg wait secs statusErr={{ statusErr }}"
    }
   ]
  },
  {
   "title": "99%ile Address Controller Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_last_client_write_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "address last_client_wr={{ last_client_wr }} contention={{ contention }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_last_client_write_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "lock last_client_wr={{ last_client_wr }} contention={{ contention }}"
    }
   ]
  },
  {
   "title": "Address Assignment Delay due to Controllers Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    },
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_count / scalar(sum(kos_ipam_last_client_write_to_address_latency_seconds_count))",
     "legendFormat": "waiters / total last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    },
    {
     "expr": "kos_ipam_address_delay_due_to_downtime_seconds_sum / kos_ipam_address_delay_due_to_downtime_seconds_count",
     "legendFormat": "avg delay secs last_client_wr={{ last_client_wr }} last_controller_start={{ last_controller_start }}"
    }
   ]
  },
  {
   "title": "Address Contention",
   "type": "graph",
   "description": "Fraction of attempt to allocate an address that fail because none is available",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - rate(kos_ipam_address_contention_bucket{le=\"0\"}[1m]) / ignoring (le) rate(kos_ipam_address_contention_bucket{le=\"+Inf\"}[1m]) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Local Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "Local Interface Creation Delay due to CA Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 {{ node_name }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / on(node_name) group_left sum(kos_agent_last_client_write_to_local_ifc_latency_seconds_count) by (node_name)",
     "legendFormat": "waiters / total {{ node_name }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_count / kos_agent_local_ifc_delay_due_to_local_ca_downtime_seconds_sum",
     "legendFormat": "avg delay secs {{ node_name }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Attachment Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_status_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Last Client Write to Remote Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_last_client_write_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "Remote Interface Creation Delay due to Remote CA Downtime",
   "type": "graph",
   "description": "The absolute number of attachments that were affected is scaled down by 100 to make it closer to the other plots and make sure the real values are not approximated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count / 100",
     "legendFormat": "num waiters / 100 {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count / on(node_name) group_left sum(kos_agent_last_client_write_to_remote_ifc_latency_seconds_count) by (node_name)",
     "legendFormat": "waiters / total {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    },
    {
     "expr": "kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_sum / kos_agent_remote_ifc_delay_due_to_remote_ca_downtime_seconds_count",
     "legendFormat": "avg delay secs {{ node_name }} last_ca_start={{ last_ca_start }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "99%ile Local Interface to Remote Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_impl_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} last_client_wr={{ last_client_wr }}"
    }
   ]
  },
  {
   "title": "virtual network relevance delay secs, per-node",
   "type": "graph",
   "description": "Per-node sum of the delays between the recorded virtual network relevance times and the real relevance times.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_vn_relevance_aggregate_delay_seconds",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99%ile of Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_exec_duration_secs_bucket{what=\"postCreate\"}[1m]))",
     "legendFormat": "{{ node }} {{ lgComplaints }}"
    }
   ]
  },
  {
   "title": "Average Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_duration_secs_sum{what=\"postCreate\"}[1m])/rate(kos_agent_attachment_exec_duration_secs_count{what=\"postCreate\"}[1m])",
     "legendFormat": "{{ node }} {{ lgComplaints }}"
    }
   ]
  },
  {
   "title": "Ping Tests/sec, by Exit Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_status_count{what=\"postCreate\"}[1m])",
     "legendFormat": "{{ node }} {{ exitStatus }} {{ lgComplaints }}"
    }
   ]
  }
 ]
}
{
 "title": "KOS Internals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_worker_count", "legendFormat": "ca @ {{ instance }}" },
    { "expr": "kos_ipam_worker_count", "legendFormat": "ipam @ {{ instance }}" },
    {
     "expr": "kos_subnet_validator_worker_count ",
     "legendFormat": "sv @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Number of CA, By Fabric Name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kos_agent_fabric_count) by (fabric)",
     "legendFormat": "{{ fabric }}"
    }
   ]
  },
  {
   "title": "KOS git commit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kos_agent_version",
     "legendFormat": "ca {{ git_commit }} @ {{ instance }}"
    },
    {
     "expr": "kos_ipam_version",
     "legendFormat": "ip {{ git_commit }} @ {{ instance }}"
    },
    {
     "expr": "kos_subnet_validator_version",
     "legendFormat": "sv {{ git_commit }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Enqueue Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_adds_total[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Dequeue Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_queue_duration_seconds_count[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Requeue Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_retries_total[1m])",
     "legendFormat": "{{ name }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_workqueue_depth", "legendFormat": "{{ name }} @ {{ instance }}" }
   ]
  },
  {
   "title": "Subnet Validator Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"sv\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_subnet_update_latency_seconds_sum[1m])) without (err, statusErr)",
     "legendFormat": "spent on updates"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_live_list_latency_seconds_sum[1m])) without (err)",
     "legendFormat": "spent on live lists"
    }
   ]
  },
  {
   "title": "99th Percentile Subnet Validator Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}  status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_live_list_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Average Subnet Validator Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_subnet_update_latency_seconds_sum[1m]) / rate(kos_subnet_validator_subnet_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_subnet_validator_live_list_latency_seconds_sum[1m]) / rate(kos_subnet_validator_live_list_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of Subnet Validator Call Outs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_subnet_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_subnet_validator_live_list_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} live list {{ err }}"
    }
   ]
  },
  {
   "title": "Subnet Validator Fraction of Live Lists not Needed",
   "type": "graph",
   "description": "When validating a subnet X, the Subnet Validator uses live lists to retrieve potentially conflicting subnets. Sometimes X's status is already up to date hence all processing including the live list was useless. This graph plots the ratio between useless live lists to the total of live lists.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(kos_subnet_validator_duplicate_work_count[1m]) + sum(rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m])) without (mismatch_type)) / ignoring (err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m]) / ignoring (mismatch_type, err) group_left rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "{{ mismatch_type }} mismatch"
    },
    {
     "expr": "sum(rate(kos_subnet_validator_subnet_live_vs_conflict_cache_count[1m])) without (mismatch_type) / ignoring(err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "total cache mismatches"
    },
    {
     "expr": "rate(kos_subnet_validator_duplicate_work_count[1m]) / ignoring(err) rate(kos_subnet_validator_live_list_latency_seconds_count{err=\"ok\"}[1m])",
     "legendFormat": "subnet status up to date"
    }
   ]
  },
  {
   "title": "Subnet Validator Fraction of Subnet Syncs Ended By Stale Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_stale_subnet_work_suppression_count[1m]) / ignoring (name) rate(kos_workqueue_work_duration_seconds_count{name=\"sv\"}[1m])",
     "legendFormat": "stale  / processed"
    }
   ]
  },
  {
   "title": "Subnet Validator 99th Percentile Nbr of Subnets in Live Lists results",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Subnet Validator Avg Nbr of Subnets in Live Lists Results",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_sum[1m]) / rate(kos_subnet_validator_number_of_subnets_returned_by_live_list_count[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "IPAM Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"ipam\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kos_ipam_attachment_update_latency_seconds_sum[1m])) without (err, statusErr)",
     "legendFormat": "spent on attachment updates"
    },
    {
     "expr": "sum(rate(kos_ipam_ip_lock_latency_seconds_sum[1m])) without (op, err)",
     "legendFormat": "spent on lock ops"
    }
   ]
  },
  {
   "title": "99th Percentile IPAM Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_ip_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average IPAM Call Out Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_ipam_attachment_update_latency_seconds_sum[1m]) / rate(kos_ipam_attachment_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_ipam_ip_lock_latency_seconds_sum[1m]) / rate(kos_ipam_ip_lock_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of IPAM Call Outs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_ipam_attachment_update_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} status update {{ statusErr }} {{ err }}"
    },
    {
     "expr": "rate(kos_ipam_ip_lock_latency_seconds_count[1m])",
     "legendFormat": "{{ instance }} lock {{ op }} {{ err }}"
    }
   ]
  },
  {
   "title": "Rate of Benefits from Special IPAM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kos_ipam_anticipation_used_bucket{le=\"1\"}[1m])) without (le) - sum(rate(kos_ipam_anticipation_used_bucket{le=\"0\"}[1m])) without (le)",
     "legendFormat": "clued anticipation @ {{ instance }}"
    },
    {
     "expr": "sum(rate(kos_ipam_anticipation_used_bucket{le=\"2\"}[1m])) without (le) - sum(rate(kos_ipam_anticipation_used_bucket{le=\"1\"}[1m])) without (le)",
     "legendFormat": "unclued anticipation @ {{ instance }}"
    },
    {
     "expr": "rate(kos_ipam_status_used_sum[1m])",
     "legendFormat": "status @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Connection Agent Worker Utilization, Summed Over Workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_workqueue_work_duration_seconds_sum{name=\"ca\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Fabric utilization, summed over workers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kos_agent_fabric_latency_seconds_sum[1m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Status Update From CA Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }} {{ statusErr }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average Status Update From CA Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_status_latency_seconds_sum[1m]) / rate(kos_agent_attachment_status_latency_seconds_count[1m])",
     "legendFormat": "{{ node }} {{ statusErr }} {{ err }}"
    }
   ]
  },
  {
   "title": "99th Percentile Successful Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\",err!=\"true\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average CreateLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateLocalIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average CreateRemotePort secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average DeleteLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteLocalIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Average DeleteRemotePort Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 250 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }} {{ err }}"
    }
   ]
  },
  {
   "title": "Current Number of Local Attachments",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_local_attachments", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "title": "Current Number of Remote Attachments",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_remote_attachments", "legendFormat": "{{ node }}" }
   ]
  }
 ]
}
{
 "title": "Kubernetes apiservers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[1m])) by (instance)",
     "legendFormat": "{{ instance }} total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*ipam.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ipam total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*connection-agent.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ca total"
    },
    {
     "expr": "sum(rate(apiserver_dropped_requests[1m])) by (instance)",
     "legendFormat": "{{ instance }} dropped"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=\"429\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 429"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=\"404\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 404"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"4..\",code!=\"429\",code!=\"404\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 4other"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"5..\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 5XX"
    }
   ]
  },
  {
   "title": "90th Percentile Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_latencies_bucket{verb!~\"WATCH|CONNECT|LIST\"}[1m])) by (instance,resource,le))/1.0e6",
     "legendFormat": "90th {{ instance }} {{ resource }}"
    }
   ]
  },
  {
   "title": "Avg Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_latencies_sum{verb!~\"WATCH|CONNECT|LIST\"}[1m])) by (instance,resource) / sum(rate(apiserver_request_latencies_count{verb!~\"WATCH|CONNECT|LIST\"}[1m])) by (instance,resource) / 1.0e6",
     "legendFormat": "avg {{ instance }} {{ resource }}"
    }
   ]
  },
  {
   "title": "1 sec high-water-mark of Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{ instance }} {{ requestKind }}"
    }
   ]
  },
  {
   "title": "Current Number of Long-Running Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_longrunning_gauge",
     "legendFormat": "{{ instance }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "longrunning, sum over instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (instance)",
     "legendFormat": "{{ kubernetes_namespace }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "TokenReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=\"tokenreviews\"}[1m])) by (instance, verb, code, client, contentType)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ client }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "SubjectAccessReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=\"subjectaccessreviews\"}[1m])) by (instance, verb, code, client, contentType)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ client }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "Go Heap Bytes In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{ instance }} {{ job }}" }
   ]
  },
  {
   "title": "Go GC CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes 1.18 apiservers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*ipam.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ipam total"
    },
    {
     "expr": "sum(rate(apiserver_request_count{client=~\".*connection-agent.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} ca total"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=\"429\"}[1m])) without (component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 429"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=\"404\"}[1m])) without (component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 404"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"4..\",code!=\"429\",code!=\"404\"}[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 4other"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[1m])) without (code,component,group,version,resource,subresource,scope,verb,contentType)",
     "legendFormat": "{{ instance }} 5XX"
    }
   ]
  },
  {
   "title": "90th Percentile Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope))",
     "legendFormat": "90th {{ instance }} {{ resource }}/{{ subresource }}"
    }
   ]
  },
  {
   "title": "Avg Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope) / sum(rate(apiserver_request_duration_seconds_count{verb!~\"WATCH|CONNECT|LIST\"}[1m])) without (component,group,version,verb,scope)",
     "legendFormat": "avg {{ instance }} {{ resource }}/{{ subresource }}"
    }
   ]
  },
  {
   "title": "1sec high-water-mark of Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{ instance }} {{ requestKind }}"
    }
   ]
  },
  {
   "title": "Current Number of Long-Running Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (group,version)",
     "legendFormat": "{{ instance }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "longrunning, sum over instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (instance,group,version)",
     "legendFormat": "{{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "TokenReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"tokenreviews\"}[1m])) without (component,group,version,resource,subresource,scope)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "SubjectAccessReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"subjectaccessreviews\"}[1m])) without (component,group,version,resource,subresource,scope)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "Go Heap Bytes In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{ instance }} {{ job }}" }
   ]
  },
  {
   "title": "Go GC CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Pod Resources",
 "description": "Shows resource usage of Kubernetes pods.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_label_io_kubernetes_pod_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "all pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Working Set",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum (machine_memory_bytes{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum(container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "each pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}[1m])) by (container_label_io_kubernetes_pod_name,instance)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}) by (container_label_io_kubernetes_pod_name,instance)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }} < out"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}[1m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }} > out"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }} < in"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}[1m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }} < in"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",instance=~\"^$instance$\",container_label_io_kubernetes_pod_namespace=~\"^$namespace$\"}) by (container_label_io_kubernetes_pod_name,instance)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }} {{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Resource Usage Per Node",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPUs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Throughput on eth[0-3]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\", interface=~\"eth[0-3]\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} xmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{id=\"/\", interface=~\"eth[0-3]\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} recv"
    }
   ]
  },
  {
   "title": "WS Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{id=\"/\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "fs bytes in use",
   "type": "graph",
   "description": "filesystem bytes in use by devices named /dev/vd.*",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev/vd.*\"}) without (device)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Local Storage Memory Series",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_memory_series"
    }
   ]
  },
  {
   "title": "Interal Storage Queue Length",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_indexing_queue_length"
    }
   ]
  },
  {
   "type": "text",
   "content": "<img src=\"http://prometheus.io/assets/prometheus_logo_grey.svg\" alt=\"Prometheus logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">Prometheus</span>\n\n<p style=\"margin-top: 10px;\">You're using Prometheus, an open-source systems monitoring and alerting toolkit originally built at SoundCloud. For more information, check out the <a href=\"http://www.grafana.org/\">Grafana</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects.</p>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Samples ingested (rate-5m)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_ingested_samples_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "content": "#### Samples Ingested\nThis graph displays the count of samples ingested by the Prometheus server, as measured over the last 5 minutes, per time series in the range vector. When troubleshooting an issue on IRC or Github, this is often the first stat requested by the Prometheus team. "
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Target Scrapes (last 5m)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "type": "text",
   "content": "#### Scrapes\nPrometheus scrapes metrics from instrumented jobs, either directly or via an intermediary push gateway for short-lived jobs. Target scrapes will show how frequently targets are scraped, as measured over the last 5 minutes, per time series in the range vector. Scrape Duration will show how long the scrapes are taking, with percentiles available as series. "
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prometheus_evaluator_duration_milliseconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "type": "text",
   "content": "#### Rule Evaluation Duration\nThis graph panel plots the duration for all evaluations to execute. The 50th percentile, 90th percentile and 99th percentile are shown as three separate series to help identify outliers that may be skewing the data."
  }
 ]
}